//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trail365.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trail365.UnitTests.Properties.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;deployment&gt;
        ///    &lt;id&gt;085b51847b5b680548034bbc1fc88b90cbe2f0da&lt;/id&gt;
        ///    &lt;author&gt;Werner Mairl&lt;/author&gt;
        ///    &lt;deployer&gt;Bitbucket&lt;/deployer&gt;
        ///    &lt;authorEmail&gt;werner.mairl@gmail.co&lt;/authorEmail&gt;
        ///    &lt;message&gt;v0.4.7 alpha1 improved event-dependency tracking
        ///&lt;/message&gt;
        ///    &lt;progress&gt;&lt;/progress&gt;
        ///    &lt;status&gt;Success&lt;/status&gt;
        ///    &lt;statusText&gt;&lt;/statusText&gt;
        ///    &lt;lastSuccessEndTime&gt;2019-11-21T18:35:39.6358741Z&lt;/lastSuccessEndTime&gt;
        ///    &lt;receivedTime&gt;2019-11-21T18:34:44.07 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeploymentStatusXml {
            get {
                return ResourceManager.GetString("DeploymentStatusXml", resourceCulture);
            }
        }
    }
}
