name: Build & Test & Push to Docker

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Get Version Suffix (master)
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release/') )
      run: |
         echo "::set-env name=VERSION_SUFFIX::"
         echo "::set-env name=DOCKER_REPOSITORY::app"

    - name: Get Version Suffix (not-master)
      if: ( !startsWith(github.ref, 'refs/heads/master') && !startsWith(github.ref, 'refs/heads/release/') )
      run: |
         VERSION_SUFFIX=$(git rev-list --all --count)
         echo "::set-env name=VERSION_SUFFIX::-preview${VERSION_SUFFIX}"
         echo "::set-env name=DOCKER_REPOSITORY::app-dev"

    - name: Build with dotnet
      run: dotnet build -p:DefineConstants="ASSERT" --configuration Release --version-suffix "${VERSION_SUFFIX}" --verbosity minimal
    
    - name: Build Verification Tests
      run: dotnet test tests/Trail365.UnitTests/Trail365.UnitTests.csproj --nologo --configuration Release --no-build /p:CollectCoverage=true --verbosity normal --filter Category=BuildVerification

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file ./src/Trail365.Web/Dockerfile --tag "trail365/${DOCKER_REPOSITORY}:latest"
    
    - name: Trace version info
      run: |
       echo "FULL_VERSION=${FULL_VERSION}" 
       echo "MINOR_VERSION=${MINOR_VERSION}" 
       echo "VERSION_SUFFIX=${VERSION_SUFFIX}"
       echo "DOCKER_REPOSITORY=${DOCKER_REPOSITORY}"
   
    - name: Tag the real versions
      run: |
         docker tag "trail365/${DOCKER_REPOSITORY}:latest" "trail365/${DOCKER_REPOSITORY}:${FULL_VERSION}" 
         docker tag "trail365/${DOCKER_REPOSITORY}:latest" "trail365/${DOCKER_REPOSITORY}:${MINOR_VERSION}"
      
    - name: Push the Docker images
      run: |
        docker push "trail365/${DOCKER_REPOSITORY}:${FULL_VERSION}" 
        docker push "trail365/${DOCKER_REPOSITORY}:${MINOR_VERSION}" 
        docker push "trail365/${DOCKER_REPOSITORY}:latest"
      
